name: Python Data Analysis CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install -r requirements.txt
        pip install google-auth==2.3.0 google-auth-oauthlib==0.4.6 google-api-python-client==2.0.0
    
    - name: Run Python script
      run: |
        python your_script_name.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: output-files
        path: |
          *.png
          *.csv    
    
    - name: Decode service account
      env:
        ENCODED_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_SERVICE }}
      run: |
        echo "$ENCODED_CREDENTIALS" | base64 -d > service_account.json
    - name: Run Python script
      run: |
        python Analysis of Dropout Data.py