name: Python Data Analysis CI

on:
  schedule:
    - cron: '0 9 1 * *' # 매월 1일 오전 9시
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pandas numpy xgboost shap gspread google-api-python-client
    - name: Use API Key
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo "Using the API key: $API_KEY"

    - name: Debug Base64
      env:
        ENCODED: ${{ secrets.GOOGLE_SHEET_SERVICE }}
      run: |
        echo "인코딩된 문자열 길이: ${#ENCODED}"
        echo "처음 10자: ${ENCODED:0:10}"
        echo "마지막 10자: ${ENCODED: -10}"
        echo "$ENCODED" > raw.txt
        cat raw.txt | tr -d '\n' > trimmed.txt
        base64 -d trimmed.txt > decoded.json || echo "디코딩 실패!"
    - name: Decode service account
      env:
        ENCODED_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_SERVICE }}
      run: |
        echo "$ENCODED_CREDENTIALS" | base64 -d > service_account.json
        # 보안을 위해 파일 권한 변경
        chmod 600 service_account.json
    - name: Run Python script
      run: |
        python "Gathering Dropout Data.py"
    - name: Run Python script
      run: |
        python "Analysis of Dropout Data.py"
        # 스크립트 실행 후 서비스 계정 파일 삭제 (보안 강화)
        rm -f service_account.json