name: Python Data Analysis CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy xgboost shap gspread google-api-python-client

    - name: Decode service account
      env:
        ENCODED_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_SERVICE }}
      run: |
        echo "$ENCODED_CREDENTIALS" | base64 -d > service_account.json

    - name: Run Python script
      run: |
        python "Analysis of Dropout Data.py"

    - name: Upload artifacts (optional)
      uses: actions/upload-artifact@v3
      with:
        name: output-files
        path: |
          *.csv
          *.png