name: Python Data Analysis CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pandas numpy xgboost shap gspread google-api-python-client
    - name: Debug Base64
      env:
        ENCODED: ${{ secrets.GOOGLE_SHEET_SERVICE }}
      run: |
        echo "인코딩된 문자열 길이: ${#ENCODED}"
        echo "마지막 5자: ${ENCODED: -5}"
        # 임시로 파일에 저장하여 검증
        echo "$ENCODED" > temp.txt
        base64 -d temp.txt > decoded.json || echo "디코딩 실패!"
    - name: Decode service account
      env:
        ENCODED_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_SERVICE }}
      run: |
        echo "$ENCODED_CREDENTIALS" | base64 -d > service_account.json
        # 보안을 위해 파일 권한 변경
        chmod 600 service_account.json

    - name: Run Python script
      run: |
        python "Analysis of Dropout Data.py"
        # 스크립트 실행 후 서비스 계정 파일 삭제 (보안 강화)
        rm -f service_account.json